### ISSUE TITLE
Change censor config on the go without restarting the software

### ISSUE THREAD

**Issue by prodigys1234** [solarorb93/BetaSuite#49] opened 2022-08-18 06:12 UTC
Let the betaTV window auto update when the config file is updated without having to restart the software

**Comment by solarorb93** [comment] 2022-08-18 12:20
Assuming you mean BetaVision, that is in progress - that's the next major release.  I posted a *very* rough demo video on Aug 5 in the discord you can find in my search history.

**Comment by solarorb93** [comment] 2022-08-18 12:21
Duplicate of #19 for GUI functionality

**Closed as completed by solarorb93** 2022-08-18 12:21 UTC
